
- name: Cluster reset
  shell: "kubeadm reset --force --cri-socket=/var/run/{{ container_runtime }}/{{ container_runtime }}.sock"
  register: reset_cluster

- name: Clean CNI configuration
  ansible.builtin.file:
    state: absent
    path: /etc/cni/net.d/

- name: Clean kubeconfig files
  ansible.builtin.file:
    state: absent
    path: /root/.kube/config

- name: Cluster configuration
  template:
    src: cluster-config.yaml.j2
    dest: /root/cluster-config.yaml

- name: Cluster initialisation
  shell: |
    kubeadm init \
      --config /root/cluster-config.yaml
  register: init_cluster

- name: Create Kubernetes config directory
  file:
    path: "/root/.kube/"
    state: directory

- name: Copy admin.conf to Home directory
  when: init_cluster is succeeded
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/root/.kube/config"
    owner: root
    group: root
    mode: 0755
    remote_src: true

- name: Copy admin.conf to Core Home directory
  when: init_cluster is succeeded
  copy:
    src: /root/.kube/config
    dest: "/home/core/admin.conf"
    owner: core
    group: core
    mode: 0755
    remote_src: true

- name: Setup networking with kube router
  when: init_cluster is succeeded
  delay: 2
  command: |
    kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml
  ignore_errors: true
