- name: Reset Kubernetes component
  shell: "kubeadm reset --force --cri-socket=/var/run/{{ container_runtime }}/{{ container_runtime }}.sock"
  register: reset_cluster

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm join --token {{ k8s.token }} \
                --discovery-token-unsafe-skip-ca-verification \
                --cri-socket=/var/run/{{ container_runtime }}/{{ container_runtime }}.sock \
                {{ groups['k8s-masters'][0] }}:6443
  register: join_cluster
  # See: https://github.com/jetstack/cert-manager/issues/2640 with using kubeadm + calico + cert-manager