
- name: Install k8s Pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes 

- name: Add rancher repo
  kubernetes.core.helm_repository:
    name: rancher-stable
    repo_url: https://releases.rancher.com/server-charts/stable

- name: Create cattle system namespace
  kubernetes.core.k8s:
    name: cattle-system
    kind: Namespace
    state: present

- name: Cert manager CRDs
  command: |
    kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml
  ignore_errors: true


- name: Add Jetstack repo (for cert management)
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
  
- name: Update cache
  kubernetes.core.helm:
    release_name: dummy
    release_namespace: kube-system
    state: absent
    update_repo_cache: true

# [WARNING]: The default idempotency check can fail to report changes in certain cases.
# Install helm diff >= 3.4.1 for better results.
- name: Install cert manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: 1.11.0
    namespace: cert-manager
    create_namespace: true

# TODO: fix rancher
- name: Install rancher
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-stable/rancher
    namespace: cattle-system
    set_values:
      - value: hostname=rancher.local
      # TODO: change to real password, put into secrets file
      - value: bootstrapPassword=admin