# TODO: split up

- name: Install python for ansible
  raw: sudo rpm-ostree install -y -A --idempotent python3 python3-libselinux python3-docker

- name: Install packages needed for core OS
  community.general.rpm_ostree_pkg:
    state: present
    name:
      # K8s
      - "kubelet-{{ kubernetesVersion }}"
      - "kubeadm-{{ kubernetesVersion }}"
      - "kubectl-{{ kubernetesVersion }}"
      - cri-o
      # K8s Ansible module
      - python3
      - python3-libselinux
      - python3-docker
      - python3-libs
      - python3-pip
      # GPU
      - intel-gpu-firmware
      # Editor
      - vim
      - nano
      # Was applied live but not persisted - needed for proxmox
      - qemu-guest-agent
      # NFS
      - nfs-utils-coreos
      # GO to build cni-plugins
      - go

- name: Reboot the servers
  reboot:

- name: Enables crio
  systemd:
    name: crio
    state: started
    enabled: true
   
- name: Enables kubelet
  systemd:
    name: kubelet
    state: started
    enabled: true

- name: Enables Qemu Guest Agent
  systemd:
    name: qemu-guest-agent
    enabled: true

- name: Install k8s Pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes 