# TODO: split up

- name: Install python for ansible
  raw: sudo rpm-ostree install -y -A --idempotent python3 python3-libselinux python3-docker

- name: Adds K8s repo
  copy:
    dest: "/etc/yum.repos.d/kubernetes.repo"
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install packages needed for core OS
  community.general.rpm_ostree_pkg:
    state: present
    name:
      # K8s
      - kubelet
      - kubeadm
      - kubectl
      - cri-o
      # K8s Ansible module
      - python3
      - python3-libselinux
      - python3-docker
      - python3-libs
      - python3-pip
      # GPU
      - intel-gpu-firmware
      # Editor
      - vim
      - nano

- name: Enables crio
  ansible.builtin.systemd:
    name: crio
    enabled: true

   
- name: Enables kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: true

- name: Reboot the servers
  ansible.builtin.reboot: