
- name: Install required core os packages using rpm-ostree
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - packages-install

    
- name: Enable ISCSI for longhorn
  hosts: all
  gather_facts: no
  become: yes
  roles:
    - iscsi