---

- name: Control Plane init
  hosts: k8s-masters
  become: yes
  vars_files:
    - ../.secrets.yaml
  roles:
    - kubeadm-init

- name: Workers join Master
  hosts: k8s-workers
  become: yes
  vars_files:
    - ../.secrets.yaml
  roles:
    - kubeadm-node-join

# TODO: investigate coredns deployment needing a restart
